// Generated by bin2c. Do not edit directly.

const char default_polymostaux_vs_glsl[] =
    "#glbuild(ES2) #version 100\r\n"
    "#glbuild(2)   #version 110\r\n"
    "#glbuild(3)   #version 140\r\n"
    "\r\n"
    "#ifdef GL_ES\r\n"
    "#elif __VERSION__ < 140\r\n"
    "#  define mediump\r\n"
    "#else\r\n"
    "#  define attribute in\r\n"
    "#  define varying out\r\n"
    "#endif\r\n"
    "\r\n"
    "attribute vec3 a_vertex;\r\n"
    "attribute mediump vec2 a_texcoord;\r\n"
    "\r\n"
    "uniform mat4 u_projection;\r\n"
    "\r\n"
    "varying mediump vec2 v_texcoord;\r\n"
    "\r\n"
    "void main(void)\r\n"
    "{\r\n"
    "    v_texcoord = a_texcoord;\r\n"
    "    gl_Position = u_projection * vec4(a_vertex, 1.0);\r\n"
    "}\r\n"
;

const int default_polymostaux_vs_glsl_size = 446;
